version: '3.8'

volumes:
   chart-geoserver-data:

services:
   geoserver:
      image: kartoza/geoserver:2.17.2
      volumes:
        - chart-geoserver-data:/opt/geoserver/data_dir
        - /asrc/ecr/danielv/geoserver_volumes/NASA_CHART:/opt/geoserver/NASA_CHART
        - /asrc/ecr/danielv/geoserver_volumes/ghaas:/opt/geoserver/ghaas
      ports:
        - "9996:8080"
      restart: on-failure
      env_file:
        - ../geoserver.env
