version: '2.1'

volumes:
   geoserver-data:

services:
   geoserver:
      image: kartoza/geoserver:latest
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - /asrc/ecr/danielv/geoserver_volumes/test-data:/opt/geoserver/test-data  
        - /asrc/ecr/danielv/geoserver_volumes/NEWS:/opt/geoserver/NEWS
        - /asrc/ecr/danielv/geoserver_volumes/ghaas:/opt/geoserver/ghaas
      ports:
        - "9999:8080"
      networks:
        - geo-net
      restart: on-failure
      env_file:
        - geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
networks:
    geo-net:
        driver: bridge
