version: '3.8'

services:
   geoserver:
      image: kartoza/geoserver:2.18.0
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
        - ./app-schema-config:/opt/geoserver/data_dir/app-schema-config/
      secrets:
        - source: postgis
          target: /usr/local/tomcat/webapps/geoserver/WEB-INF/classes/app-schema.properties
      ports:
        - "9998:8080"
      restart: on-failure
      env_file:
        - geoserver.env

volumes:
  geoserver-data:

secrets:
  postgis:
    external: true