version: '2.1'

volumes:
   geoserver-data-test:

services:
   geoserver:
      image: kartoza/geoserver:latest
      volumes:
          - /asrc/ecr/danielv/geoserver_volumes/app-schema-tutorial:/opt/geoserver/data_dir
          - /asrc/ecr/danielv/geoserver_volumes/test-data:/opt/geoserver/test-data  
      ports:
        - "9998:8080"
      restart: on-failure
      env_file:
        - geoserver.env
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
