version: '3.8'

volumes:
   news-geoserver-data:

services:
   geoserver:
      image: kartoza/geoserver:2.17.2
      volumes:
        - news-geoserver-data:/opt/geoserver/data_dir
        - /asrc/ecr/danielv/geoserver_volumes/NEWS:/opt/geoserver/NEWS
      ports:
        - "9999:8080"
      restart: on-failure
      env_file:
        - ../geoserver.env
