version: '3.8'

services:
   geoserver:
      image: kartoza/geoserver:2.17.2
      volumes:
        - ghaas-geoserver-data:/opt/geoserver/data_dir
        - /asrc/ecr/danielv/geoserver_volumes/ghaas:/opt/geoserver/ghaas/
      ports:
        - "9998:8080"
      restart: on-failure
      env_file:
        - ../geoserver.env

volumes:
  ghaas-geoserver-data:
